Install script fixes
gabyx/githooks pull request #146
Opened 2024-03-19 11:28 UTC by mruz

On openSUSE I have just `linux` in `$OSTYPE` and filenames have `macos` in the name https://github.com/gabyx/Githooks/releases/tag/v2.8.0

2024-03-19 15:25 UTC, gabyx commented
This is good to go, some small change needed since I want to leave `darwin` in there, because its not necessary to change it. might be to brittle.

2024-03-20 09:15 UTC, mruz commented
For `darwin` I'm getting:
![image (8)](https://github.com/gabyx/Githooks/assets/2629882/deae38e9-cbdb-42e6-8b96-1854cdf5491f)

2024-03-20 09:22 UTC, mruz commented
```sh
$ curl --silent --location https://api.github.com/repos/gabyx/Githooks/releases/tags/v2.8.0 \
    | jq --raw-output ".assets[] | select( (.name | contains(\"darwin\")) and (.name | contains(\"arm64\")) ) | .browser_download_url"

$ curl --silent --location https://api.github.com/repos/gabyx/Githooks/releases/tags/v2.8.0 \
    | jq --raw-output ".assets[] | select( (.name | contains(\"macos\")) and (.name | contains(\"arm64\")) ) | .browser_download_url"
https://github.com/gabyx/Githooks/releases/download/v2.8.0/githooks-2.8.0-macos.arm64.tar.gz
```

2024-03-21 11:25 UTC, gabyx commented
Ah, ok thanks for the hint! But could you leave `darwin` in the paltform script and make an `darwin` to `macos` overwrite in the `install.sh` script. That might be better!

Thanks for the patch.

2024-03-21 11:26 UTC, gabyx requested changes

2024-03-21 11:55 UTC, gabyx commented
@mruz : I changed it, will merge in a second.

2024-03-21 16:42 UTC, merged